name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Despliegue FTP a pruebagencia.online

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Deploy FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.pruebagencia.online
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/app/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
            **/archivos_cargados/**
            conexion.php
            conexion/conexion.php
            **/*.sql
            **/*.log
